// <auto-generated />
namespace Poject2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class deletday2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletday2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806262121392_deletday2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
